apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: graphqlschemas.graphql.gloo.solo.io
spec:
  group: graphql.gloo.solo.io
  names:
    kind: GraphQLSchema
    listKind: GraphQLSchemaList
    plural: graphqlschemas
    singular: graphqlschema
    shortNames:
      - gqls
      - ggqls
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
